export const LOAD_PRODUCTS_REQUESTED = 'products/LOAD_PRODUCTS_REQUESTED';
export const LOAD_PRODUCTS_SUCCESS = 'products/LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_FAILURE = 'products/LOAD_PRODUCTS_FAILURE'; 